version: '3'

services:

    postgres:
        container_name: postgres
        image: postgres:10.5-alpine
        environment:
            POSTGRES_DB: bot
            POSTGRES_USER: thombot
            POSTGRES_PASSWORD: tacos
            PG_ROOT_PASSWORD: twotacos
        ports:
            - 5430:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    bot:
        container_name: bot
        build:
            context: .
            dockerfile: build/bot/Dockerfile
        tty: true
        depends_on:
            - postgres
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"