version: '3'

services:
    bot:
        container_name: bot
        build:
            context: .
            dockerfile: build/bot/Dockerfile
    postgres:
        container_name: postgres
        image: postgres:10.5-alpine
        environment:
            POSTGRES_DB: bot
            POSTGRES_USER: thombot
            POSTGRES_PASSWORD: tacos
            PG_ROOT_PASSWORD: twotacos
        ports:
            - 5430:5432
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: docker@docker.com
            PGADMIN_DEFAULT_PASSWORD: docker