version: '3'

services:
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: docker@docker.com
            PGADMIN_DEFAULT_PASSWORD: docker